name: CI

on: 
  push:
    branches: 
      - 'main'
  pull_request:

permissions:
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                persist-credentials: false
            - name: Setup Java JDK
              uses: actions/setup-java@v5
              with:
                distribution: temurin
                java-version: 25
                cache: gradle
            - name: Gradle test task
              run: ./gradlew --no-daemon clean test
